### ISSUE TITLE
Can't find the package on PyPi

### ISSUE THREAD

**Issue by maxpmaxp** [asher/chronos-python#1]
Why haven't you published the package on PyPi?

**Comment by solarkennedy** [comment]
@maxpmaxp did you end up using this library or did you use a different one? If so, which?

**Comment by maxpmaxp** [comment]
@solarkennedy I use this one, just copied the source to my project. Made some custom modifications.

**Comment by asher** [comment]
@maxpmaxp feel free to send PR's for your modifications

**Comment by keshavdv** [comment]
Available now at https://pypi.python.org/pypi/chronos-python. @asher, I'd like to make you a maintainer of the package so you can push new versions. If you're interested, can you share your pypi username?

**Comment by asher** [comment]
Thanks keshav! My pypi username is afeldman.

**Comment by keshavdv** [comment]
Added you to the pypi project,
