### ISSUE TITLE
new version in pypi

### ISSUE THREAD

**Issue by Rob-Johnson** [asher/chronos-python#12]
hi @asher,

We'd like to push a new version of chronos-python to pypi. Right now, yourself and @keshavdv are maintainers of the package - how would you feel about extending that to @solarkennedy and I? We're actively working on with chronos-python at Yelp and we'd like to help with it's development :)

Thanks.

**Comment by keshavdv** [comment]
@asher 

Since @Rob-Johnson and @solarkennedy expressed interest in continued development of chronos-python, I have added both as maintainers of the package on PyPI. As active users, I hope they will be able to keep this package up-to-date and continue to add features/bugfixes.

**Comment by Rob-Johnson** [comment]
Thanks @keshavdv 

@asher, I'm going to push [this commit](https://github.com/Rob-Johnson/chronos-python/commit/43539a0aaa2ed6703791f7162e54d4e4b0f52bf3) as version 0.34.0 to pypi. Could you please merge that PR and tag the commit as 0.34.0, or, could you provide commit access to the repo so we can do this ourselves.

Thanks

**Comment by Rob-Johnson** [comment]
@keshavdv could you please add @solarkennedy and I as maintainers in testpypi too?

**Comment by asher** [comment]
@Rob-Johnson @solarkennedy I've made you both committers. 

Cheers,
Asher

**Comment by Rob-Johnson** [comment]
great, thanks @asher
