### ISSUE TITLE
parent job

### ISSUE THREAD

**Issue by jerrybean** [asher/chronos-python#16]
Chronos supports parent job,can i add parents job using chronos-python

**Comment by Rob-Johnson** [comment]
hi jerrybean,

I don't quite get what you mean - any job with a schedule can be used as a parent for a dependent job, so you can use the [client.add](https://github.com/asher/chronos-python/blob/master/chronos/__init__.py#L71) function for this. Is that what you meant?

**Comment by jerrybean** [comment]
hi Rob-Johnson,you are right! I do something wrong before,thank you!

**Comment by Rob-Johnson** [comment]
no problem.
