### ISSUE TITLE
Chronos 3.0.0 support

### ISSUE THREAD

**Issue by xkrt** [asher/chronos-python#33]
Hi!

Yesterday Chronos v3.0.0 was released and looks like there is API incompotability with previous version.
Look https://github.com/mesos/chronos/releases
Also, note that new versions of Chronos now will be published only to Docker Hub, so `CHRONOSVERSION=3.0.0 make itests` will not work.

**Comment by xkrt** [comment]
Also, I think you should decide: chronos-python will support multiple Chronos versions or will support latest stable version only?

README.md declares that `chronos-python uses Travis to test against multiple versions of Chronos`, but I see that in fact tests runs only against ver 2.4.0 now https://travis-ci.org/asher/chronos-python.

Currently I work on Ansible module for deploying jobs on Chronos and use chronos-python for that as dependency and I'm interesting only in latest stable release of Chronos (3.0.0 now).

**Comment by Rob-Johnson** [comment]
yeah, this was on my radar @xkrt.

We certainly need backward compatibility: here at Yelp we're running a forked version 2.4, and it'll be a while before we upgrade.

It's a shame they've stopped publishing deb packages. I'll have a think about how we can adjust the itests to work with v3.

**Comment by paddycarey** [comment]
Hi, now that #35 is merged into master would it be possible to cut a new PyPI release?

**Comment by solarkennedy** [comment]
New release (1.0.0) is out.
