### ISSUE TITLE
Library doesn't recognize leader change

### ISSUE THREAD

**Issue by ivanaslamov** [asher/chronos-python#38]
HI @asher, hey I noticed that the library doesn't recognize when a leader changes and even if you include all servers in the list during initialization it still tries to communicate only to the first one in the list replying with:

``` html
<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>\n<title>Error 500 </title>\n</head>\n<body>\n<h2>HTTP ERROR: 500</h2>\n<p>Problem accessing /v1/scheduler/graph/csv. Reason:\n<pre>    Error proxying request to leader (maybe the leadership just changed?)\n\nError:\njava.net.ConnectException: Connection timed out (Connection timed out)\n\tat java.net.PlainSocketImpl.socket
```

is there a workaround for this or am I missing something, thank you.

**Comment by solarkennedy** [comment]
That is surprising, leader election works for me.

However this is *not* a problem with the library. Any HTTP request sent to chronos like that will return that same error.

Are you running the different chronos processes in a restricted network mode? (in docker in NAT) so they can't talk to each other?
