### ISSUE TITLE
Override container entrypoint

### ISSUE THREAD

**Issue by almahmoud** [asher/chronos-python#45]
Is there a way and/or would it be feasible to add a way to override the default entrypoint from the container image (or alternatively even just a flag to force empty it?)

**Comment by solarkennedy** [comment]
Currently no (sorta), but it is already?.

This python library just passes fields on to the Chronos API. Here are the docs:
https://github.com/mesos/chronos/blob/c1348ddfd80eb8f888418805005066c230fc6ad2/docs/docs/api.md#job-configuration

Look at the `shell` arg, which defaults to true, which *already* overwrites the default entrypoint.

Is the default entrypoint of a container image *currently* getting in your way?

**Comment by almahmoud** [comment]
We are looking into making all of our runners act more consistently by overriding things and it is getting in our way in one of the runners, I could not quickly google a way to override the entrypoint for our chronos runner (but admittedly I have no experience with chronos). It seems this is already not a problem here, this behavior is what we're trying to sync to, so this is perfect, I should've looked more into it.

Thanks for the response and sorry for the noise!
